### ISSUE TITLE
t/02_config.t fails on most installations

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/optex#3]
On most of my smokers the test suite fails:

```
...
#   Failed test 'symlink, no-module'
#   at t/02_config.t line 37.
#          got: ''
#     expected: '-M
# '

#   Failed test 'symlink, alias'
#   at t/02_config.t line 39.
#          got: ''
#     expected: 'yes'
# Looks like you failed 2 tests of 5.
t/02_config.t ... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/5 subtests 
...
```

**Comment by eserte** [comment]
Still the same problem with App-optex-v0.0.11

**Comment by kaz-utashiro** [comment]
It seems `/usr/bin/env perl` is not working.  The file has to be executable because it is called from symbolic link.  Hope next fix to work.

**Comment by kaz-utashiro** [comment]
v0.0.12 seems to be working.
http://www.cpantesters.org/author/U/UTASHIRO.html#App-optex

I don't why this page is not updated.
http://matrix.cpantesters.org/?dist=App-optex+v0.0.12

**Comment by kaz-utashiro** [comment]
I appreciate a lot your effort in testing environments.
